### ISSUE TITLE
feat: Can't support zstd compression

### ISSUE THREAD

**Issue by jun0315** [aloneguid/parquet-online#3]
System.NotSupportedException: No compression codec for Zstd is available on this platform (arch: Wasm, rt: browser-wasm, native: False) at Parquet.File.DataColumnReader.ReadDataPageV2Async(PageHeader ph, PackedColumn pc, Int64 maxValues) at Parquet.File.DataColumnReader.ReadAsync(CancellationToken cancellationToken) at Parquet.ParquetExtensions.ReadAsTableAsync(ParquetReader reader, TableReaderProgressCallback progressCallback, Nullable`1 rowGroupIndex) at ParquetViewer.Shared.DataView.LoadAsync()

**Comment by aloneguid** [comment]
Thanks for reporting. This is a known issue due to the fact there was no web-assembly zstd implementation available. I'm currently upgrading `IronCompress` to include non-native option so this should be ready around tomorrow.
